package dao;

import annotation.MyBatisRepository;
import entity.CompanyInfoWithBLOBs;

@MyBatisRepository
public interface CompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    int insert(CompanyInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    int insertSelective(CompanyInfoWithBLOBs record);
}