package dao;

import annotation.MyBatisRepository;
import entity.Picdata;

@MyBatisRepository
public interface PicdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    int insert(Picdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    int insertSelective(Picdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    Picdata selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Picdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Picdata record);
}