package entity;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.COMPANY_NAME
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.E_MAIL
     *
     * @mbggenerated
     */
    private String information;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.CONTAC_CO
     *
     * @mbggenerated
     */
    private String contacCo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.TEL_CO
     *
     * @mbggenerated
     */
    private String telCo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.FB
     *
     * @mbggenerated
     */
    private String fb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.TW
     *
     * @mbggenerated
     */
    private String tw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.E_MAIL
     *
     * @mbggenerated
     */
    private String addrCo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    public CompanyInfo() {
    }

    public CompanyInfo(String companyName, String information, String contacCo, String telCo, String phone, String fb, String tw, String addrCo, String eMail) {
        this.companyName = companyName;
        this.information = information;
        this.contacCo = contacCo;
        this.telCo = telCo;
        this.phone = phone;
        this.fb = fb;
        this.tw = tw;
        this.addrCo = addrCo;
        this.eMail = eMail;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getInformation() {
        return information;
    }

    public void setInformation(String information) {
        this.information = information;
    }

    public String getContacCo() {
        return contacCo;
    }

    public void setContacCo(String contacCo) {
        this.contacCo = contacCo;
    }

    public String getTelCo() {
        return telCo;
    }

    public void setTelCo(String telCo) {
        this.telCo = telCo;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFb() {
        return fb;
    }

    public void setFb(String fb) {
        this.fb = fb;
    }

    public String getTw() {
        return tw;
    }

    public void setTw(String tw) {
        this.tw = tw;
    }

    public String getAddrCo() {
        return addrCo;
    }

    public void setAddrCo(String addrCo) {
        this.addrCo = addrCo;
    }

    public String geteMail() {
        return eMail;
    }

    public void seteMail(String eMail) {
        this.eMail = eMail;
    }

    @Override
    public String toString() {
        return "CompanyInfo{" +
                "companyName='" + companyName + '\'' +
                ", information='" + information + '\'' +
                ", contacCo='" + contacCo + '\'' +
                ", telCo=" + telCo +
                ", phone=" + phone +
                ", fb='" + fb + '\'' +
                ", tw='" + tw + '\'' +
                ", addrCo='" + addrCo + '\'' +
                ", eMail='" + eMail + '\'' +
                '}';
    }
}