package entity;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.COMPANY_NAME
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.CONTAC_CO
     *
     * @mbggenerated
     */
    private String contacCo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.TEL_CO
     *
     * @mbggenerated
     */
    private Integer telCo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.PHONE
     *
     * @mbggenerated
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.FB
     *
     * @mbggenerated
     */
    private String fb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.TW
     *
     * @mbggenerated
     */
    private String tw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public CompanyInfo(String companyName, String contacCo, Integer telCo, Integer phone, String fb, String tw, String eMail) {
        this.companyName = companyName;
        this.contacCo = contacCo;
        this.telCo = telCo;
        this.phone = phone;
        this.fb = fb;
        this.tw = tw;
        this.eMail = eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.COMPANY_NAME
     *
     * @return the value of company_info.COMPANY_NAME
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.CONTAC_CO
     *
     * @return the value of company_info.CONTAC_CO
     *
     * @mbggenerated
     */
    public String getContacCo() {
        return contacCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.TEL_CO
     *
     * @return the value of company_info.TEL_CO
     *
     * @mbggenerated
     */
    public Integer getTelCo() {
        return telCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.PHONE
     *
     * @return the value of company_info.PHONE
     *
     * @mbggenerated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.FB
     *
     * @return the value of company_info.FB
     *
     * @mbggenerated
     */
    public String getFb() {
        return fb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.TW
     *
     * @return the value of company_info.TW
     *
     * @mbggenerated
     */
    public String getTw() {
        return tw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.E_MAIL
     *
     * @return the value of company_info.E_MAIL
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }
}