package entity;

public class ItemType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_type.CLASS_NAME
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_type.CLASS_TYPE
     *
     * @mbggenerated
     */
    private Integer classType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_type.CLASS_TYPE
     *
     * @mbggenerated
     */
    private String classNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_type
     *
     * @mbggenerated
     */
    public ItemType(String className, Integer classType,String classNote) {
        this.className = className;
        this.classType = classType;
        this.classNote = classNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_type.CLASS_NAME
     *
     * @return the value of item_type.CLASS_NAME
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_type.CLASS_TYPE
     *
     * @return the value of item_type.CLASS_TYPE
     *
     * @mbggenerated
     */
    public Integer getClassType() {
        return classType;
    }

    public String getClassNote() {
        return classNote;
    }

    public void setClassNote(String classNote) {
        this.classNote = classNote;
    }
}