package entity;

public class Items {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.ITEM_CODE
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.MATERIAL
     *
     * @mbggenerated
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.CLASS
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.CLASS_TYPE
     *
     * @mbggenerated
     */
    private Integer classType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.G_MODEL
     *
     * @mbggenerated
     */
    private String gModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.PRICE
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated
     */
    public Items(String id, String itemName, String itemCode, String material, String className, Integer classType, String gModel, Float price) {
        this.id = id;
        this.itemName = itemName;
        this.itemCode = itemCode;
        this.material = material;
        this.className = className;
        this.classType = classType;
        this.gModel = gModel;
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ID
     *
     * @return the value of items.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ITEM_NAME
     *
     * @return the value of items.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.ITEM_CODE
     *
     * @return the value of items.ITEM_CODE
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.MATERIAL
     *
     * @return the value of items.MATERIAL
     *
     * @mbggenerated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.CLASS
     *
     * @return the value of items.CLASS
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.CLASS_TYPE
     *
     * @return the value of items.CLASS_TYPE
     *
     * @mbggenerated
     */
    public Integer getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.G_MODEL
     *
     * @return the value of items.G_MODEL
     *
     * @mbggenerated
     */
    public String getgModel() {
        return gModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.PRICE
     *
     * @return the value of items.PRICE
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }
}