package entity;

public class Picdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picdata.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picdata.PIC_NAME
     *
     * @mbggenerated
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picdata.PIC_PATH
     *
     * @mbggenerated
     */
    private String picPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picdata
     *
     * @mbggenerated
     */
    public Picdata(String id, String picName, String picPath) {
        this.id = id;
        this.picName = picName;
        this.picPath = picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picdata.ID
     *
     * @return the value of picdata.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picdata.PIC_NAME
     *
     * @return the value of picdata.PIC_NAME
     *
     * @mbggenerated
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picdata.PIC_PATH
     *
     * @return the value of picdata.PIC_PATH
     *
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }
}